#FROM docker.io/centos
FROM centos:lsm

WORKDIR /root
ARG user
ARG dir
ARG port

RUN cat /etc/redhat-release
RUN getconf LONG_BIT
RUN echo "arg1 : ${user:-laravel}"
RUN echo ${dir:-demo}
RUN echo ${port:-8000}
RUN mkdir install
COPY installphp.sh install
RUN chmod +x install/installphp.sh
COPY laravel.sh install
RUN chmod +x install/laravel.sh
COPY test.sh install

RUN yum install yum-utils -y
RUN rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
RUN rpm -Uvh https://rpms.remirepo.net/enterprise/remi-release-7.rpm
RUN yum-config-manager --disable remi-php72
RUN yum-config-manager --enable remi-php74
RUN yum list php-common
RUN ./install/installphp.sh
RUN php -v
RUN yum install -y curl
RUN yum install -y nginx
RUN curl -sS https://getcomposer.org/installer | php  
RUN cp composer.phar /usr/bin/composer
RUN composer global require laravel/installer


COPY nginx.conf install
COPY php-fpm.conf install
COPY www.conf install
ADD sites-available.tar.gz install
RUN ls -l
RUN yum install sudo -y
RUN useradd ${user:-laravel}
WORKDIR "install"
RUN ls -l

RUN yes | cp -pR sites-available /home/${user:-laravel}/sites-available
RUN yes | cp -pR nginx.conf /etc/nginx/
RUN yes | cp -pR www.conf /etc/php-fpm.d/
RUN yes | cp -pR php-fpm.conf /etc/
RUN mkdir /var/run/php-fpm
RUN touch /var/run/php-fpm/php-fpm.pid
RUN touch /var/run/php-fpm/php-fpm.sock

#COPY sites-available /home/${user:-laravel}/
#COPY www.conf /etc/php
RUN ls -l /home/laravel/

#USER ${user:-laravel}
RUN sudo -i -u ${user:-laravel} -H sh -c "composer global require laravel/installer"

RUN sudo -i -u ${user:-laravel} -H sh -c "echo 'export PATH=$PATH:~/.config/composer/vendor/bin/' >> ~/.bashrc"
RUN sudo -i -u ${user:-laravel} -H sh -c ". ~/.bashrc"
RUN sudo -i -u ${user:-laravel} -H sh -c "laravel new ${dir:-demo}"
RUN sudo -i -u ${user:-laravel} -H sh -c "cd /home/${user:-laravel}/${dir:-demo}"

#WORKDIR "/home/laravel"
#RUN sh -c "laravel new ${dir:-demo}"
#RUN pkill nginx
#RUN nginx

#WORKDIR "install"
#USER root
CMD ["/usr/sbin/init"]
#CMD sh install/test.sh
#WORKDIR "/home/${user:-laravel}/${dir:-demo}"


