apiVersion: v1
kind: Service
metadata:
  name: service-tomcat
  labels:
    app: service-tomcat
spec:
  ports:
    - port: 8080
      protocol: TCP
#      targetPort: 9376
  clusterIP: 10.105.138.223
  selector:
    app: tomcatcnt
    typical: frontend
  type: NodePort
#  clusterIP: 192.168.56.4
#kubectl expose deployment hello-minikube --type=NodePort --port=8080
#kubectl port-forward service/hello-minikube 7080:8080
#kubectl port-forward --address 0.0.0.0 service/service-tomcat 8080:8080