apiVersion: v1
kind: Service
metadata:
  name: service-oracle
  labels:
    app: service-oracle
spec:
  ports:
    - port: 1522
      protocol: TCP
  clusterIP: 10.105.138.222
  selector:
    app: oraclecnt
    typical: frontend
  type: NodePort
