apiVersion: v1
kind: Service
metadata:
  name: service-tomcat
  labels:
    app: service-tomcat
spec:
  ports:
    - port: 8080
      protocol: TCP
  clusterIP: 10.105.138.223
  selector:
    app: tomcatcnt
    typical: frontend
  type: NodePort